# ==========================================================
#  Configuración Inicial para Alacritty
# ==========================================================

[window]
# Relleno (padding) interior de la ventana para que el texto no esté pegado a los bordes.
padding = { x = 12, y = 12 }

# Opacidad del fondo (0.0 es totalmente transparente, 1.0 es totalmente opaco).
opacity = 0.98

[font]
# --- ¡LA PARTE MÁS IMPORTANTE! ---
# Asegúrate de que el nombre de la familia coincida exactamente con la Nerd Font que instalaste.
# Ejemplos: "FiraCode Nerd Font", "JetBrainsMono Nerd Font", "MesloLGS NF".
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

# Tamaño de la fuente.
size = 12.0

# Activar ligaduras de la fuente (si usas una como Fira Code o JetBrains Mono).
[font.ligatures]
enable = true

[colors]
# Tema de ejemplo: Catppuccin Macchiato.
# Puedes encontrar muchísimos temas aquí: https://github.com/alacritty/alacritty-theme
primary = { background = "0x24273a", foreground = "0xcad3f5" }
normal = { black = "0x494d64", red = "0xed8796", green = "0xa6da95", yellow = "0xeed49f", blue = "0x8aadf4", magenta = "0xc6a0f6", cyan = "0x91d7e3", white = "0xb8c0e0" }
bright = { black = "0x5b6078", red = "0xed8796", green = "0xa6da95", yellow = "0xeed49f", blue = "0x8aadf4", magenta = "0xc6a0f6", cyan = "0x91d7e3", white = "0xa5adce" }

[cursor]
# Estilo del cursor. Opciones: Block, Underline, Beam.
style = { shape = "Block", blinking = "On" }

[keyboard]
# Permite que Neovim maneje sus propios atajos de teclado sin conflictos.
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
